### ISSUE TITLE
FMC schematic: AD9117 DVDD output shorted to DVDDIO

### ISSUE THREAD

**Issue by mkiepiela** [sinara-hw/Shuttler#22]
DVDD (internal LDO output) must be disconnected from DVDDIO when supplied from external source (V_ADJ).
![obraz](https://user-images.githubusercontent.com/25741678/114858415-b8e6b400-9de9-11eb-99e2-cc583447b9bb.png)

Disconnect and bypass DVDD output with 1 uF to GND.

![obraz](https://user-images.githubusercontent.com/25741678/114859342-e849f080-9dea-11eb-8dfb-58021be130de.png)

**Comment by dhslichter** [comment]
Do we need to maintain the potential for adjustability of the DVDDIO rail?  At least in my view, it is preferable to always require that the DVDDIO rail be at 1.8 V.  This lowers power dissipation on the DAC as well as the FPGA driving the digital lines, and running 1.8V signals instead of 3.3V signals reduces EMI.

**Comment by gkasprow** [comment]
the LVDS won't work with 3.3V anyway. So we should support 1.8 and 2.5V only and this is the way I design all FMC boards. We should add 0R + 1uF to support 2.5V VADJ. We have a place for PCB for that.

**Comment by gkasprow** [comment]
![obraz](https://user-images.githubusercontent.com/4325054/119221730-f2999180-baf0-11eb-9ce7-c5d5103066ed.png)
