### ISSUE TITLE
Shuttler analog bandwidth 

### ISSUE THREAD

**Issue by jmatyas** [sinara-hw/Shuttler#36]
According to wiki, Shuttler's analog bandwidth is supposed to be around ~15 MHz, however after some testing on Shuttler v1.0 it seems to be closer to 6 MHz :

![image](https://user-images.githubusercontent.com/48015058/221841901-1f6c4163-4aca-4e36-affe-6cd34d7a6664.png)

To achieve those results:

- a sinusoidal signal with a given frequency was generated on DAC channel
- peak-peak amplitude on one of the DAC channel's analog output (after AFE) was measured
- signal frequency was changed and the measurement was repeated

**Comment by kaolpr** [comment]
@dhslichter @adbr8389 @gkasprow How do you find current bandwidth? Do we need to fix AFE to follow statement in Wiki (~15 MHz)?

**Comment by kaolpr** [comment]
AFAIK this was measured before AFE. Tomorrow I'll ask @jmatyas to provide more details.

**Comment by kaolpr** [comment]
But the main question is - was this intended? The simulation @gkasprow provided in #28 seems to confirm that DAC_AFE (the one on FMC) was designed for ~6 MHz.

**Comment by dhslichter** [comment]
the op amps have 100 MHz GBW so I thought we would be able to get more than this? However, if we can't go any higher than what is shown here, that is probably still acceptable.

**Comment by adbr8389** [comment]
What is the IC used for the differential amp after the ADA4896's? If it has some small capacitive input, I think it could explain the small discrepancy between Daniel's estimation of a 33 pF cap for a 15 MHz bandwidth.

**Comment by dhslichter** [comment]
The 33 pF = 15 MHz was only a coarse estimate, I think this seems reasonable. Glad to see that this increased the bandwidth @kaolpr. Next question is whether we should increase further (e.g. 10 pF, or just DNP this capacitor). I would be in favor of testing with capacitors removed and ensuring the op amp outputs are stable (they should be, since we are at G=5). This gives maximum bandwidth out of the FMC card. One can always use following components to reduce the bandwidth as desired for applications, but this would make the FMC card maximally useful for different tasks.
